apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-function
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: python-function
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: python-function
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: python-function
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: python-function
    spec:
      containers:
      - image: tapdemoregistry.azurecr.io/tanzu/tanzu-supply-chain/python-function-tap-dev@sha256:7f1f1ef2c2e1a1419d1b378459a3e0db79a71c1b70a5d34d28f9f0d998c85850
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

